api_cloud/api_api/urls.py
from django.conf.urls import url
from api_api import api

urlpatterns = [
    url(r'^list/', api.api_list, name="api_list"),
    url(r'^data/', api.get_api_data, name="api_data"),
    url(r'^new/', api.api_new, name="api_new"),
    url(r'^add/', api.api_add_save, name="api_add"),
    url(r'^detail/', api.api_detail, name="api_detail"),
    url(r'^edit/', api.api_edit_save, name="api_edit"),
    url(r'^del/', api.api_delete, name="api_del"),
    url(r'^result/', api.api_get_execute_result, name="api_result"),
    url(r'^batch/', api.api_get_batch_execute_result, name="api_batch"),
    url(r'^move/', api.api_batch_move, name="api_move"),
]

api_cloud/api_cloud/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from api_user import urls as user_urls
from api_api import urls as api_urls
from api_hosts import urls as hosts_urls
from api_project import urls as project_urls
from api_user import login


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', login.home, name="home"),
    url(r'^api/home/', login.home, name="home"),
    url(r'^api/user/', include(user_urls, namespace="api_user")),
    url(r'^api/api/', include(api_urls, namespace="api_api")),
    url(r'^api/hosts/', include(hosts_urls, namespace="api_hosts")),
    url(r'^api/project/', include(project_urls, namespace="api_project")),
]

api_cloud/api_hosts/urls.py
from django.conf.urls import url
from api_hosts import hosts

urlpatterns = [
    url(r'^list/', hosts.hosts_list, name="hosts_list"),
    url(r'^change/', hosts.hosts_change, name="hosts_change"),
    url(r'^new/', hosts.hosts_new_hosts, name="hosts_new"),
    url(r'^add/', hosts.hosts_add_save, name="hosts_add"),
    url(r'^edit/', hosts.hosts_edit_save, name="hosts_edit"),
    url(r'^del/', hosts.hosts_delete, name="hosts_del"),
    url(r'^detail/', hosts.hosts_get_detail, name="hosts_detail"),
    url(r'^current/', hosts.hosts_show_current, name="hosts_current"),
]

api_cloud/api_project/urls.py
from django.conf.urls import url
from api_project import project


urlpatterns = [
    url(r'^list/', project.project_list, name="project_list"),
    url(r'^new/', project.project_new, name="project_new"),
    url(r'^detail/', project.project_detail, name="project_detail"),
    url(r'^add/', project.project_add, name="project_add"),
    url(r'^edit/', project.project_edit, name="project_edit"),
    url(r'^del/', project.project_delete, name="project_del"),
    url(r'^tree/', project.all_project_tree, name="project_tree"),
    url(r'^user_tree/', project.user_project_tree, name="project_user_tree"),
    url(r'per_tree/', project.user_permission_project_tree, name="project_per_tree"),
]

api_cloud/api_user/urls.py
from django.conf.urls import url
import api_user.login
import api_user.user

urlpatterns = [
    url(r'^real/', api_user.login.user_get_real_name, name="user_real_name"),
    url(r'^login/', api_user.login.user_login,  name="user_login"),
    url(r'^logout/', api_user.login.user_logout, name="user_logout"),
    url(r'^list/', api_user.user.user_list, name="user_list"),
    url(r'^new/', api_user.user.user_new, name="user_new"),
    url(r'^add/', api_user.user.user_add, name="user_add"),
    url(r'^edit/', api_user.user.user_edit, name="user_edit"),
    url(r'^detail/', api_user.user.user_detail, name="user_detail"),
    url(r'^del/', api_user.user.user_delete, name="user_del"),
    url(r'^password/', api_user.user.user_modify_password, name="user_password"),
    url(r'^modify/', api_user.user.user_save_password, name="user_modify"),
]

api_cloud/api_api/models.py
from django.db import models


# Create your models here.
class ApiApi(models.Model):
    name = models.CharField(max_length=100)
    project_id = models.IntegerField(blank=True, null=True)
    api_http_type = models.IntegerField(blank=True, null=True)
    api_url = models.CharField(max_length=500, blank=True, null=True)
    url_list = models.TextField(blank=True, null=True)
    api_domain = models.CharField(max_length=100, blank=True, null=True)
    api_method = models.IntegerField(blank=True, null=True)
    api_headers = models.TextField(blank=True, null=True)
    api_body_type = models.IntegerField(blank=True, null=True)
    api_body_value = models.TextField(blank=True, null=True)
    api_expect_result = models.TextField(blank=True, null=True)
    api_real_result = models.TextField(blank=True, null=True)
    api_is_success = models.IntegerField(blank=True, null=True)
    remarks = models.TextField(blank=True, null=True)
    creater = models.IntegerField(blank=True, null=True)
    create_time = models.DateTimeField(blank=True, null=True)
    update_time = models.DateTimeField(blank=True, null=True)
    last_execute_time = models.DateTimeField(blank=True, null=True)
    status = models.IntegerField(blank=True, null=True)

api_cloud/api_hosts/models.py
from django.db import models


# Create your models here.
class ApiHosts(models.Model):
    name = models.CharField(max_length=100)
    content = models.TextField(blank=True)
    status = models.IntegerField(blank=True)
    is_current = models.BooleanField(blank=True)
    create_time = models.DateTimeField(blank=True)

api_cloud/api_project/models.py
# -*- coding:utf8 -*-
from django.db import models


# Create your models here.
class ApiProject(models.Model):
    name = models.CharField(max_length=100)
    parent_id = models.IntegerField(blank=True, null=True)
    level = models.IntegerField(blank=True, default=1)
    api_document = models.CharField(max_length=1000, blank=True, null=True)
    status = models.IntegerField(blank=True, default=1)
    create_time = models.DateTimeField(blank=True)

api_cloud/api_user/models.py
from django.db import models


class Permission(models.Model):
    user_id = models.IntegerField(blank=True, null=True)
    project_id = models.IntegerField(blank=True, null=True)

api_cloud/api_api/views.py
from django.shortcuts import render

# Create your views here.

api_cloud/api_hosts/views.py
from django.shortcuts import render

# Create your views here.

api_cloud/api_project/views.py
from django.shortcuts import render

# Create your views here.

api_cloud/api_user/views.py
from django.shortcuts import render

# Create your views here.

api_cloud/templates/api_detail.html
{% extends "base.html" %}
{% block title %}接口详情{% endblock %}
{% block extra_head %}
    <script src="/static/js/public/jquery.jsonview.js"></script>
    <link rel="stylesheet" href="/static/css/jquery.jsonview.css">
    <script src="/static/js/api/detail.js"></script>
    <script src="/static/js/api/add.js"></script>
{% endblock %}
{% block content %}
<div id="center"  class="centerDiv">
    <div class="api_total">
        <div class="form-group">
            <div class="form-inline" role="form" style="margin-top: 10px;">
                <!--接口名称和所属项目-->
                <input id="api_id_txt" value="{{ api_info.id }}" style="display: none">
                 <div class="new_line_div">
                    <label>所属项目：{{ project_name }}</label>
                 </div>
                 <div class="new_line_div">
                     <input type="text" class="api_input" placeholder="接口名称" id="api_name_txt" style="width: 100%" value="{{ api_info.name }}">
                 </div>
                <!--接口名称和所属项目-->

                <!--请求url等-->
                <div class="new_line_div">
                <div class="form-group" style="display: inline-block;width: 100%;">
                    <select class="form-control" id="api_http_type" style="width: 150px;">
                            <option value="1" {% if api_info.api_http_type == 1 %}selected="selected" {% endif %}>HTTP</option>
                            <option value="2" {% if api_info.api_http_type == 2 %}selected="selected" {% endif %}>HTTPS</option>
                    </select>
                    <input type="text" class="api_input" placeholder="Domain" id="api_domain_txt" style="width: 200px;" value="{{ api_info.api_domain }}">
                    <input type="text" placeholder="Url" class="api_input" style="width:50%;" id="api_url_txt" value="{{ api_info.api_url }}">

                    <select class="form-control" id="api_method">
                            <option value="1" {% if api_info.api_method == 1 %}selected="selected" {% endif %}>GET</option>
                            <option value="2" {% if api_info.api_method == 2 %}selected="selected" {% endif %}>POST</option>
                    </select>
                    <button class="btn btn-primary" data-toggle="collapse" data-target="#url_params">URL Params</button>
                    <button class="btn btn-primary" data-toggle="collapse" data-target="#url_headers">Headers</button>
                    <button class="btn btn-primary" data-toggle="collapse" data-target="#url_remarks">备注</button>
                </div>
                </div>
                <!--请求url等-->

                <!--请求参数、请求头、备注-->
                <div class="new_line_div">
                    <div id="url_params" class="collapse">
                        <input value='{{ api_info.url_list }}' style="display: none" id="default_url_list">
                    </div>
                    <div id="url_headers" class="collapse">
                        <input value='{{ api_info.api_headers }}' style="display: none" id="default_headers">
                    </div>
                    <div id="url_remarks" class="collapse" style="margin-top: 5px;">
                        <textarea class="form-control"  style="width: 100%;height: 100px;resize: vertical;" id="remarks_data">{{ api_info.remarks }}</textarea>
                    </div>
                </div>
                <!--请求参数、请求头、备注-->

                <!--请求体-->
                <div id="post_body_div" style="display: none">
                    <div class="new_line_div">
                        <div class="btn-group" id="body_btn">
                            <button type="button" class="btn btn-default active" id="formdata_btn">form-data</button>
                            <button type="button" class="btn btn-default" id="urlencoded_btn">x-www-form-urlencoded</button>
                            <button type="button" class="btn btn-default" id="raw_btn">raw</button>
                        </div>
                    </div>
                    <div class="new_line_div" id="api_body_div">
                        <input style="display: none" value="{{ api_info.api_body_type }}" id="body_type_txt">
                        <input value='{{ api_info.api_body_value }}' style="display: none" id="default_body_value">
                        <div id="body_form_data"></div>
                        <div id="body_url_data" style="display: none"></div>
                        <div id="body_raw" style="display: none">
                            <textarea class="form-control"  style="width: 100%;height: 200px;resize: vertical;" id="body_raw_data"></textarea>
                        </div>
                    </div>
                </div>
                <!--请求体-->

                <!--请求按钮-->
                <div class="new_line_div">
                    <button class="btn btn-success" style="width: 80px;" id="api_edit_save_btn">保存</button>
                    <button class="btn btn-info" style="width: 80px;" id="api_execute_btn">执行</button>
                    <label id="execute_result_txt"></label>
                </div>
                <!--请求按钮-->
            </div>
        </div>
    </div>

    <!--执行结果-->
    <div>
        <div style="padding-left: 10px;"><label>执行时间：{{ api_info.last_execute_time }}</label></div>
       <div style="width: 50%;float: left; padding: 10px;overflow:auto;">
           <label>预期执行结果：</label>
           <input id="expect_result_value_txt" style="display: none;" value="{{ api_info.api_expect_result }}">
           <div id="api_expect_result" style="padding-bottom: 40px;"></div>
       </div>
       <div style="width: 50%;float: left; padding: 10px;">
           <label>本次执行结果：</label>
           <div id="api_real_result" style="padding-bottom: 40px;overflow:auto;">
               <div id="loading"></div>
           </div>
           <div id="api_real_result_no_form" style="display: none;"></div>
       </div>
    </div>
    <!--执行结果-->
</div>
{% endblock %}

api_cloud/templates/api_list.html
{% extends "base_public.html" %}
{% block title %}接口管理{% endblock %}
{% block extra_head %}
    <script src="/static/js/api/list.js"></script>
{% endblock %}
{% block leftinfo %}
    <a href='{%url "api_hosts:hosts_current" %}' target="_blank"  class="list-group-item" id="showHosts">查看服务器 Hosts</a>
    <a href='{%url "api_api:api_list" %}'  class="list-group-item active" id="showApis">接口管理</a>
    <div id="uid_value" style="display: none">{{ uid }}</div>
    <div id="project_tree" class="ztree"></div>
{% endblock %}
{% block rightinfo %}
    <div style="display: none" id="project_id_val"></div>
    <form class="form-inline">
        <div id="btn_div">
            <a  class="btn btn-info" style="width: 80px;" id="refresh_btn">刷新</a>
            <a  target="_blank" class="btn btn-primary" style="width: 80px;" id="new_api_btn">添加</a>
            <a  class="btn btn-danger" style="width: 80px;" id="batch_del_btn">批量删除</a>
            <a  class="btn btn-success" style="width: 80px;" id="batch_exe_btn">批量执行</a>
            <a  class="btn btn-warning" style="width: 80px;" id="batch_move_btn" data-toggle="modal" data-target="#move_api">批量移动</a>
        </div>
        <div class="form-group" >
            <label id="data_counts"></label>
            <label id="page_counts"></label>
        </div>
        <div class="form-group" style="margin-left: 20px;" id="show_data_page"></div>
    </form>
    <div id="loading" style="text-align: center;" ></div>
    <div class="alert alert-info alert-dismissable" id="exe_result">

        <div id="exe_result_txt">请选择项目查看接口</div>
    </div>
    <table class="table table-bordered table-striped" id="api_list"></table>

<!-- 模态框（Modal） -->
<div class="modal fade" id="move_api" tabindex="-1" role="dialog"
   aria-labelledby="myModalLabel" aria-hidden="true">
   <div class="modal-dialog">
      <div class="modal-content">
         <div class="modal-header">
            <button type="button" class="close"
               data-dismiss="modal" aria-hidden="true">
                  &times;
            </button>
            <h4 class="modal-title" id="myModalLabel">
               选择移动到的项目
            </h4>
         </div>
         <div class="modal-body" >
            <div class="ztree" id="show_all_project"></div>
         </div>
         <div class="modal-footer">
            <button type="button" class="btn btn-default"
               data-dismiss="modal">关闭
            </button>
            <button type="button" class="btn btn-primary" id="save_move_btn">
               保存
            </button>
         </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal -->
</div>

{% endblock %}

api_cloud/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}-API</title>
    <!-- Bootstrap 文件 -->
    <link rel="shortcut icon" href="/static/images/favicon.ico" />
    <link href="http://apps.bdimg.com/libs/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://apps.bdimg.com/libs/jquery/2.0.0/jquery.min.js"></script>
    <script src="http://apps.bdimg.com/libs/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="/static/js/public/jquery.validate.min.js"></script>
    <script src="/static/js/public/messages_cn.js"></script>
    <script src="/static/js/public/bootstrap-treeview.js"></script>
    <script src="/static/js/public/jquery.ztree.all-3.5.min.js"></script>
    <script src="/static/js/public/jquery.ztree.core-3.5.min.js"></script>
    <script src="/static/js/public/jquery.ztree.excheck-3.5.min.js"></script>
    <link rel="stylesheet" href="/static/css/zTreeStyle/zTreeStyle.css">
    <link rel="stylesheet" href="/static/css/user/login.css">
    <link rel="stylesheet" href="/static/css/api/table.css">
    <link rel="stylesheet" href="/static/css/api/api.css">
    <script src="/static/js/public/public.js"></script>
    {% block extra_head %}{% endblock %}
</head>
<body>
<div class="topMenu">
        <label class="logoFont"><a href="{% url 'home' %}">云平台接口管理系统</a></label>
        {% block head_info %}{% endblock %}
</div>
{% block content %}
{% endblock %}
 <div class="bottomMenu">
        Copyright©2015-2016 云平台质量管理部 All Rights Reserved.<span style="margin-left: 20px;">如果您有任何问题，请联系管理员：<a href="mailto:yangjing@smartisan.com">yangjing@smartisan.com</a></span>
 </div>
</body>
</html>

api_cloud/templates/base_public.html
{% extends "base.html" %}
{% block head_info %}
    <a href='{%url "api_user:user_logout" %} '>注销</a>
    <a href='{%url "api_user:user_password" %} ' target="_blank">修改密码</a>
    <a id="user_real_name"></a>
{% endblock %}
{% block content %}
    <div id="center" class="centerDiv">
        <div class="leftPanel" id="leftMenu">
            {% block leftinfo %}{% endblock %}
        </div>
        <div class="rightPanel" id="rightInfo">
            {% block rightinfo %}{% endblock %}
        </div>
    </div>
{% endblock %}

api_cloud/templates/hosts_add.html
{% extends "base.html" %}
{% block title %}新建 Hosts{% endblock %}
{% block extra_head %}
    <script src="/static/js/hosts/add.js"></script>
{% endblock %}
{% block content %}
    <div id="center" class="centerDiv">
        <div style="width: 800px;text-align: center;margin-left: auto;margin-right: auto;padding-top: 20px;">
            <form class="form-horizontal" role="form">
                    <div class="form-group">
                        <label for="hosts_name" class="col-sm-2 control-label">Hosts 名称</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="hosts_name" placeholder="Hosts 名称" required="required" >
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="hosts_content" class="col-sm-2 control-label">内容</label>
                        <div class="col-sm-10">
                            <textarea id="hosts_content" class="form-control" rows="25" spellcheck="FALSE">{{ hosts_info.content }}</textarea>
                        </div>
                    </div>


                    <div class="form-group">
                        <div style="text-align: center;">
                            <button type="button" class="btn btn-primary" style="width: 80px;" id="add_hosts_save">保存</button>
                        </div>
                    </div>
                </form>
        </div>
    </div>
{% endblock %}

api_cloud/templates/hosts_current.html
{% extends "base.html" %}
{% block title %}当前服务器 Hosts{% endblock %}
{% block extra_head %}
    <script src="/static/js/hosts/add.js"></script>
{% endblock %}
{% block content %}
    <div id="center" class="centerDiv">
        <div style="width: 400px;text-align: center;margin-left: auto;margin-right: auto;padding-bottom: 40px;">
            <div style="margin-top: 20px; margin-bottom: 20px;text-align: center;">
                <p class="text-left">服务器 IP 地址：{{ cur_ip }}</p>
            </div>
            {% for hosts in cur_hosts %}
                <div style="text-align: center">
                <p class="text-left">{{ hosts }}</p>
                </div>

            {% endfor %}
        </div>
    </div>
{% endblock %}

api_cloud/templates/hosts_detail.html
{% extends "base.html" %}
{% block title %}Hosts 详情{% endblock %}
{% block extra_head %}
    <script src="/static/js/hosts/edit.js"></script>
{% endblock %}
{% block content %}
    <div id="center" class="centerDiv">
        <div style="width: 800px;text-align: center;margin-left: auto;margin-right: auto;padding-top: 20px;">
            <input id="hosts_id" value="{{ hosts_info.id }}" style="display: none;">
            <form class="form-horizontal" role="form">
                    <div class="form-group">
                        <label for="hosts_name" class="col-sm-2 control-label">Hosts 名称</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="hosts_name" placeholder="Hosts 名称" required="required" value={{ hosts_info.name }}>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="hosts_content" class="col-sm-2 control-label">内容</label>
                        <div class="col-sm-10">
                            <textarea id="hosts_content" class="form-control" rows="25" spellcheck="FALSE">{{ hosts_info.content }}</textarea>
                        </div>
                    </div>


                    <div class="form-group">
                        <div style="text-align: center;">
                            <button type="button" class="btn btn-primary" style="width: 80px;" id="edit_hosts_save">保存</button>
                        </div>
                    </div>
                </form>
        </div>
    </div>
{% endblock %}

api_cloud/templates/hosts_list.html
{% extends "base_public.html" %}
{% block title %}Hosts管理{% endblock %}
{% block extra_head %}
    <script src="/static/js/hosts/list.js"></script>
{% endblock %}
{% block leftinfo %}
    <a href='{%url "api_user:user_list" %}'  class="list-group-item" id="showProjects">用户管理</a>
    <a href='{%url "api_project:project_list" %}'  class="list-group-item" id="showProjects">项目管理</a>
    <a href='{%url "api_hosts:hosts_list" %}' id="showHosts" class="list-group-item active">服务器 Hosts</a>
{% endblock %}
{% block rightinfo %}

    <form class="form-inline">
        <div>
            <a href='{%url "api_hosts:hosts_new" %}' target="_blank" class="btn btn-primary" style="width: 80px;">添加</a>
            <a href='{%url "api_hosts:hosts_current" %}' target="_blank" style="float: right;" class="btn btn-default">查看当前系统 Hosts</a>
        </div>
        <div class="form-group" ><label>共计：{{ hosts_info.paginator.count }} 条，共 {{ hosts_info.paginator.num_pages }} 页</label></div>
        <div class="form-group" style="margin-left: 20px;">
            <ul class="pagination">
                {% if hosts_info.has_previous %}
                    <li><a href="?page={{ hosts_info.previous_page_number }}">前一页</a></li>
                {% else %}
                    <li><a class="disabled">前一页</a></li>
                {% endif %}
                {% for p in page_range %}
                    {% ifequal p hosts_info.number %}
                      <li class="active"><a>{{p}}</a></li>
                    {% else %}
                      <li><a href="?page={{p}}" title="第{{p}}页">{{p}}</a><li>
                    {% endifequal %}
                {% endfor %}
                {% if hosts_info.has_next %}
                <li><a href="?page={{ hosts_info.next_page_number }}">后一页</a></li>
                {% else %}
                <li><a class="disabled">后一页</a></li>
                {% endif %}
            </ul>
        </div>
    </form>
    <table class="table table-bordered table-striped" id="api_list">
		<thead>
			<tr>
				<th>ID</th>
				<th>名称</th>
				<th>Hosts内容</th>
                <th>操作</th>
			</tr>
		</thead>
        {% for hosts in hosts_info %}
             <tr>
                 <td>{{ hosts.id }}</td>
                 <td><a href='{% url "api_hosts:hosts_detail" %}?hosts_id={{ hosts.id }}'  target="_blank">{{ hosts.name }}</a></td>
                 <td><textarea class="form-control" rows="5" style="resize: vertical;" readonly="readonly">{{ hosts.content }}</textarea></td>
                 <td width="280px;">
                     {% if hosts.is_current %}
                         <button type="button" class="btn btn-warning" disabled="disabled">当前 Hosts</button>
                     {% else %}
                         <a class="btn btn-info" href='{% url "api_hosts:hosts_change" %}?hosts_id={{ hosts.id }}' style="width: 80px;">切换</a>
                         <a class="btn btn-danger" href='#' style="width: 80px;" id="delete{{ hosts.id }}">删除</a>
                         <a href='{%url "api_hosts:hosts_new" %}?hosts_id={{ hosts.id }}' target="_blank" class="btn btn-primary">复制添加</a>
                     {% endif %}

                 </td>
             </tr>
        {% endfor %}
	</table>
{% endblock %}

api_cloud/templates/project_detail.html
{% extends "base.html" %}
{% block title %}编辑项目{% endblock %}
{% block extra_head %}
<script src="/static/js/project/detail.js"></script>
{% endblock %}
{% block content %}
<div id="center" class="centerDiv">
    <div style="width: 600px;text-align: center;margin-left: auto;margin-right: auto;padding-top: 40px;">
        <form class="form-horizontal" role="form">
            <div class="form-group">
                <label for="hosts_name" class="col-sm-3 control-label">所属项目</label>
                <div class="col-sm-9" >
                    <div class="ztree" id="project_parent_id"></div>
                </div>
            </div>
            <input style="display: none" value="{{ project_info.id }}" id="project_id">
            <div class="form-group">
                <label for="hosts_name" class="col-sm-3 control-label">项目名称</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" id="project_name" placeholder="项目名称" required="required" value="{{ project_info.name }}">
                </div>
            </div>

            <div class="form-group">
                <label for="hosts_name" class="col-sm-3 control-label">项目文档</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" id="api_document" placeholder="项目文档" required="required" value="{{ project_info.api_document }}">
                </div>
            </div>

            <div class="form-group">
                <div style="text-align: center;">
                    <button type="button" class="btn btn-primary" style="width: 80px;" id="edit_project_save">保存</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

api_cloud/templates/refuse.html
{% extends "base.html" %}
{% block title %}无权限{% endblock %}
{% block content %}
    <div id="center" class="centerDiv">
        <div style="text-align: center;line-height: 500px;">
            <span style="color: #3f8bb7;font-size:120px;">Refuse</span>
        </div>
    </div>
{% endblock %}

api_cloud/templates/user_list.html
{% extends "base_public.html" %}
{% block title %}用户管理{% endblock %}
{% block extra_head %}
    <script src="/static/js/user/list.js"></script>
{% endblock %}
{% block leftinfo %}
    <a href='{%url "api_user:user_list" %}'  class="list-group-item active" id="showProjects">用户管理</a>
    <a href='{%url "api_project:project_list" %}'  class="list-group-item" id="showProjects">项目管理</a>
    <a href='{%url "api_hosts:hosts_list" %}' id="showHosts" class="list-group-item">服务器 Hosts</a>
{% endblock %}
{% block rightinfo %}

    <form class="form-inline">
        <div>
            <a href='{%url "api_user:user_new" %}' target="_blank" class="btn btn-primary" style="width: 80px;">添加</a>
        </div>
        <div class="form-group" ><label>共计：{{ user_info.paginator.count }} 条，共 {{ user_info.paginator.num_pages }} 页</label></div>
        <div class="form-group" style="margin-left: 20px;">
            <ul class="pagination">
                {% if user_info.has_previous %}
                    <li><a href="?page={{ user_info.previous_page_number }}">前一页</a></li>
                {% else %}
                    <li><a class="disabled">前一页</a></li>
                {% endif %}
                {% for p in page_range %}
                    {% ifequal p user_info.number %}
                      <li class="active"><a>{{p}}</a></li>
                    {% else %}
                      <li><a href="?page={{p}}" title="第{{p}}页">{{p}}</a><li>
                    {% endifequal %}
                {% endfor %}
                {% if user_info.has_next %}
                <li><a href="?page={{ user_info.next_page_number }}">后一页</a></li>
                {% else %}
                <li><a class="disabled">后一页</a></li>
                {% endif %}
            </ul>
        </div>
    </form>
    <table class="table table-bordered table-striped" id="user_list">
		<thead>
			<tr>
				<th>ID</th>
				<th>用户名</th>
				<th>真实姓名</th>
                <th>邮箱</th>
                <th>是否管理员</th>
                <th>操作</th>
			</tr>
		</thead>
        {% for users in user_info %}
             <tr>
                 <td>{{ users.id }}</td>
                 <td><a href='{% url "api_user:user_detail" %}?user_id={{ users.id }}'  target="_blank">{{ users.username }}</a></td>
                 <td>{{ users.first_name }}</td>
                 <td>{{ users.email }}</td>
                 {% if users.is_superuser %}
                 <td style="color:#72e66a">{{ users.is_superuser }}</td>
                 {% else %}
                 <td>{{ users.is_superuser }}</td>
                 {% endif %}
                 <td>
                     <a class="btn btn-danger" href='#' style="width: 80px;" id="delete{{ users.id }}">删除</a>
                 </td>
             </tr>
        {% endfor %}
	</table>
{% endblock %}